name: 'Setup Prerequisites'
description: 'Sets up the required software components'
runs:
  using: "composite"
  steps:
    - name: Setup .NET SDK 9.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Setup .NET SDK 10.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
        dotnet-quality: preview

    - name: Setup just
      uses: extractions/setup-just@v3
