name: Setup Prerequisites
description: Sets up required software components
runs:
  using: composite
  steps:
    # Avoid wasting type on updating man pages which are not used anyway
    - run: sudo rm -f /var/lib/man-db/auto-update
      if: runner.os == 'Linux'

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Setup .NET SDK 10.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
        dotnet-quality: preview

    - name: Setup just
      uses: extractions/setup-just@v3
