//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gapotchenko.GnuTK.Diagnostics {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DiagnosticResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DiagnosticResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gapotchenko.GnuTK.Diagnostics.DiagnosticResources", typeof(DiagnosticResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory &apos;{1}&apos; specified for a built-in GNU toolkit &apos;{0}&apos; is not found..
        /// </summary>
        internal static string BuiltInToolkitXDirectoryYNotFound {
            get {
                return ResourceManager.GetString("BuiltInToolkitXDirectoryYNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; process cannot be started..
        /// </summary>
        internal static string CannotStartProcessX {
            get {
                return ResourceManager.GetString("CannotStartProcessX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program arguments &apos;{0}&apos; and &apos;{1}&apos; cannot be specified simultaneously..
        /// </summary>
        internal static string ConflictingProgramArgumentsXY {
            get {
                return ResourceManager.GetString("ConflictingProgramArgumentsXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find &apos;{0}&apos; module..
        /// </summary>
        internal static string ModuleXNotFound {
            get {
                return ResourceManager.GetString("ModuleXNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No suitable toolkit with strict GNU semantics is found..
        /// </summary>
        internal static string SuitableStrictToolkitNotFound {
            get {
                return ResourceManager.GetString("SuitableStrictToolkitNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No suitable toolkit with strict GNU semantics named {0} is found..
        /// </summary>
        internal static string SuitableStrictToolkitXNotFound {
            get {
                return ResourceManager.GetString("SuitableStrictToolkitXNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No suitable GNU toolkit is found..
        /// </summary>
        internal static string SuitableToolkitNotFound {
            get {
                return ResourceManager.GetString("SuitableToolkitNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No suitable GNU toolkit named {0} is found..
        /// </summary>
        internal static string SuitableToolkitXNotFound {
            get {
                return ResourceManager.GetString("SuitableToolkitXNotFound", resourceCulture);
            }
        }
    }
}
