# Gapotchenko.GnuTK
#
# Copyright © Gapotchenko and Contributors
#
# File introduced by: Oleksiy Gapotchenko
# Year of introduction: 2025

set fallback := true
set windows-shell := ["powershell", "-c"]

# -----------------------------------------------------------------------------

# Show the help for this justfile
@help:
    just --list

clean:
    cd Packaging; just clean
    cd Setup; just clean
