set windows-shell := ["gnu-tk", "-c"]

# Show the help for this justfile
@help:
    just --list

pack:
    cd scripts && chmod +x *.sh && ./prepare-platforms.sh
    cp -l ../../../README.md gnu-tk/README.md
    rm -rf bin obj && mkdir bin obj
    cp gnu-tk/package.json obj/package.json
    @cd gnu-tk && npm version 0.0.0-reset > /dev/null
    cd gnu-tk && npm version `xq ../../../Mastering/.NET/Version.props -x //Project/PropertyGroup/Version`
    cd gnu-tk && npm pkg delete devDependencies scripts.format
    npm pack ./gnu-tk --pack-destination bin
    mv -f obj/package.json gnu-tk/package.json

clean:
    rm -rf bin obj
    rm -f gnu-tk/README.md
    cd scripts && ./clean-platforms.sh
