set windows-shell := ["gnu-tk", "-c"]

# Show the help for this justfile
@help:
    just --list

pack:
    cd scripts && ./prepare-platforms.sh
    rm -rf bin && mkdir bin
    @cd gnu-tk && npm version 0.0.0-reset > /dev/null
    cd gnu-tk && npm version `xq ../../../Mastering/.NET/Version.props -x //Project/PropertyGroup/Version`
    npm pack ./gnu-tk --pack-destination bin
    @cd gnu-tk && npm version 0.0.0 > /dev/null
    @cd scripts && ./cleanup-platforms.sh
