set fallback := true
set windows-shell := ["powershell", "-c"]

# Show the help for this justfile
@help:
    just --list

[group("build")]
[parallel]
pack: (_component-pack "NPM") (_component-pack "Portable") (_component-pack "Setup")

[group("build")]
[parallel]
clean: (_component-clean "NPM") (_component-clean "Portable") (_component-clean "Setup")

_component-pack name:
    cd "{{ name }}"; just pack

_component-clean name:
    cd "{{ name }}"; just clean
