name: Experiment

on:
  workflow_dispatch:

env:
  ContinuousIntegrationBuild: true
  DOTNET_NOLOGO: true
  SuppressNETCoreSdkPreviewMessage: true

jobs:
  platform-build:
    name: Run a aunner
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Diagnostic (Windows)
        if: runner.os == 'Windows'
        run: |
          where msys2bash.cmd

      - uses: actions/upload-artifact@v4
        with:
          name: experiment-artifacts-${{ matrix.os }}
          path: |
            Source/**/bin/Release/**/publish/
            !Source/**/*.pdb
            !Source/**/*.dbg
            !Source/**/*.dSYM
