name: Tested Build

on:
  workflow_dispatch:

jobs:
  platform-build:

    name: Platform Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup prerequisites
        uses: ./.github/actions/setup-prerequisites

      - name: Test
        run: just test

      - name: Build platform-dependent artifacts
        run: just platform-build

      - uses: actions/upload-artifact@v4
        with:
          name: gnu-tk-artifacts-${{ matrix.os }}
          path: |
            Source/**/bin/Release/**/publish/
            !Source/**/*.pdb
            !Source/**/*.dbg
            !Source/**/*.dSYM
          if-no-files-found: error

  publish:

    name: Publish
    needs: platform-build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup prerequisites
        uses: ./.github/actions/setup-prerequisites

      - run: sudo apt install -y xq

      - name: Publish artifacts
        run: just publish

      - uses: actions/download-artifact@v4
        with:
          path: Source

      - name: Publish platform-dependent artifacts
        run: just platform-publish

      - uses: actions/upload-artifact@v4
        with:
          name: gnu-tk-artifacts-publish
          path: |
            Source/**/bin/Release/nuget/*.nupkg
            Source/Packaging/**/bin/*.tgz
          if-no-files-found: error
