# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Tested Build

on:
  workflow_dispatch:

jobs:
  build-platform:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]    

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
        dotnet-quality: preview
    - name: Setup just
      uses: extractions/setup-just@v3
    - name: Test
      run: just test
    - name: Publish AOT
      run: just publish-aot
