name: Tested Build

on:
  workflow_dispatch:

env:
  DOTNET_NOLOGO: true
  SuppressNETCoreSdkPreviewMessage: true

jobs:
  platform-build:

    name: Platform Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup prerequisites
        uses: ./.github/actions/setup-prerequisites

      - name: Setup MSYS2
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2

      - name: Setup Cygwin
        if: runner.os == 'Windows'
        uses: cygwin/cygwin-install-action@v6

      - name: Diagnostic
        run: just diagnostic

      - name: Diagnostic of GNU toolkits on Windows
        if: runner.os == 'Windows'
        shell: bash
        run: GNU_TK_TOOLKIT=msys2 just diagnostic; GNU_TK_TOOLKIT=cygwin just diagnostic

      - name: Test
        run: just test

      - name: Build platform-dependent artifacts
        run: just platform-build

      - uses: actions/upload-artifact@v4
        with:
          name: gnu-tk-artifacts-${{ matrix.os }}
          path: |
            Source/**/bin/Release/**/publish/
            !Source/**/*.pdb
            !Source/**/*.dbg
            !Source/**/*.dSYM
          if-no-files-found: error

  publish:

    name: Publish
    needs: platform-build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup prerequisites
        uses: ./.github/actions/setup-prerequisites

      - run: sudo apt-get install -y xq

      - name: Setup security environment
        env:
          GP_OSS_ASSEMBLY_SNK: ${{ secrets.GP_OSS_ASSEMBLY_SNK }}
        run: |
          echo $GP_OSS_ASSEMBLY_SNK | base64 --decode > gp-oss-assembly.snk

      - name: Create .env file
        run: |
          cat <<EOF >.env
          AssemblyOriginatorKeyFile=`pwd`/gp-oss-assembly.snk
          EOF

      - name: Publish artifacts
        run: just publish

      - uses: actions/download-artifact@v4
        with:
          path: Source
          merge-multiple: true

      - name: Publish platform-dependent artifacts
        run: just platform-publish

      - uses: actions/upload-artifact@v4
        with:
          name: gnu-tk-artifacts-publish
          path: |
            Source/**/bin/Release/nuget/*.nupkg
            Source/Packaging/**/bin/*.tgz
          if-no-files-found: error
