# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Tested Build

on:
  workflow_dispatch:

jobs:
  build-platform-artifacts:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, windows-11-arm, macOS-latest]    

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
        dotnet-quality: preview
    - name: Setup just
      uses: extractions/setup-just@v3
    - name: Test
      run: just test
    - name: Publish AOT
      run: just _publish-aot
    - uses: actions/upload-artifact@v4
      with:
        name: gnu-tk-executable-${{ matrix.os }}
        path: |
          Source/Gapotchenko.GnuTK/bin/Release/**/publish/
          !Source/Gapotchenko.GnuTK/bin/Release/**/publish/*.pdb
        if-no-files-found: error
