name: Tested Build

on:
  workflow_dispatch:

jobs:
  build-platform:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
        dotnet-quality: preview
    - name: Setup just
      uses: extractions/setup-just@v3
    - name: Test
      run: just test
    - name: Build platform-dependent artifacts
      run: just build-platform
    - uses: actions/upload-artifact@v4
      with:
        name: gnu-tk-artifacts-${{ matrix.os }}
        path: |
          Source/**/bin/Release/**/publish/
          !Source/**/*.pdb
          !Source/**/*.dbg
          !Source/**/*.dSYM
        if-no-files-found: error
